version: '3'

services:
  strapi:
    image: strapi/strapi
    container_name: "strapi"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      CLOUDINARY_NAME: plpbs
      CLOUDINARY_KEY: 179454326984431
      CLOUDINARY_SECRET: rhCqxXe5Y-dxNTfpzUMoSvASV28
      NODE_ENV: development

    volumes:
      - ./:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - strapidata:/var/lib/postgresql/
      - ./backups:/backups/

volumes:
  strapidata:
