version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: ameciclo/ameciclo
    docker:
      - image: circleci/buildpack-deps:stretch
orbs:
  node: circleci/node@5.0.0
  cypress: cypress-io/cypress@1.29.0

workflows:
  build:
    jobs:
      - checkout
      - cypress/install:
          executor: cypress/base-14
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json"
            }}
          working_directory: frontend
          build: npm run build
          requires:
            - checkout
      - cypress/run:
          executor: cypress/base-14
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json"
            }}
          working_directory: frontend
          start: npm start
          store_artifacts: true
          record: true
          requires:
            - cypress/install
      - backend/install:
          requires:
            - checkout
      - backend/test:
          requires:
            - backend/install

jobs:
  checkout:
    docker:
      - image: cimg/base:stable
    working_directory: ~/ameciclo
    steps:
      - checkout:
          path: ~/ameciclo

  backend/install:
    working_directory: ~/ameciclo/backend
    docker:
      - image: node:14.19.0
    steps:
      - checkout:
          path: ~/ameciclo
      - node/install:
          install-yarn: true
          node-version: '14.19.0'
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Run tests
          command: npm test

  backend/test:
    working_directory: ~/ameciclo/backend
    docker:
      - image: node:14.19.0
    steps:
      - node/install:
          install-yarn: true
          node-version: '14.19.0'
      - run:
          name: Run tests
          command: npm test


