version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: ameciclo/ameciclo
    docker:
      - image: circleci/buildpack-deps:stretch
orbs:
  node: circleci/node@5.0.0
  cypress: cypress-io/cypress@1.29.0

workflows:
  build:
    jobs:
      - cypress/install:
          executor: cypress/base-14
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json"
            }}
          working_directory: frontend
          build: npm run build
      - cypress/run:
          executor: cypress/base-14
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json"
            }}
          working_directory: frontend
          start: npm start
          store_artifacts: true
          record: true
          requires:
            - cypress/install
      - backend_install
      - backend_test:
          requires:
            - backend_install

jobs:
  backend_install:
    working_directory: ~/ameciclo/backend
    docker:
      - image: node:14.19.0
    steps:
      - checkout:
          path: ~/ameciclo
      - node/install:
          install-yarn: true
          node-version: '14.19.0'
      - node/install-packages:
          pkg-manager: yarn 
      - persist_to_workspace:
          root: ~/ameciclo/backend
          paths:
            - .


  backend_test:
    working_directory: ~/ameciclo/backend
    docker:
      - image: node:14.19.0
    steps:
      - attach_workspace:
          at: ~/ameciclo/backend
      - node/install:
          install-yarn: true
          node-version: '14.19.0'
      - run:
          name: Run tests
          command: npm test


