version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: ameciclo/ameciclo
    docker:
      - image: circleci/buildpack-deps:stretch
orbs:
  node: circleci/node@5.0.0
  cypress: cypress-io/cypress@1.29.0

workflows:
  build:
    jobs:
      - checkout
      - cypress/install:
          executor: cypress/base-14
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json"
            }}
          working_directory: frontend
          build: npm run build
          requires:
            - checkout
      - cypress/run:
          executor: cypress/base-14
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json"
            }}
          working_directory: frontend
          start: npm start
          store_artifacts: true
          record: true
          requires:
            - cypress/install
      # - test_frontend:
      #     requires:
      #       - checkout
      # - test_backend:
      #     requires:
      #       - checkout

jobs:
  checkout:
    docker:
      - image: cimg/base:stable
    working_directory: ~/ameciclo
    steps:
      - checkout:
          path: ~/ameciclo

  build_frontend:
    working_directory: ~/ameciclo/frontend
    docker:
      - image: node:17.4.0
    steps:
      - run:
          command: 'ls'
      - run:
          name: Run build
          command: 'npm run build'




