version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: ameciclo/ameciclo
    docker:
      - image: circleci/buildpack-deps:stretch
orbs:
  node: circleci/node@5.0.0
  cypress: cypress-io/cypress@1.29.0

workflows:
  build:
    jobs:
      - checkout
      - cypress/install:
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json"
            }}
      - cypress/run:
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json"
            }}
          working_directory: frontend
          start: npm start
          requires:
            - checkout
      # - test_frontend:
      #     requires:
      #       - checkout
      # - test_backend:
      #     requires:
      #       - checkout

jobs:
  checkout:
    docker:
      - image: cimg/base:stable
    working_directory: ~/ameciclo
    steps:
      - checkout:
          path: ~/ameciclo

  # test_frontend:
  #   working_directory: ~/ameciclo/frontend
  #   docker:
  #     - image: node:16.14.0
  #   steps:
  #     - cypress/run


