version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: ameciclo/ameciclo
    docker:
      - image: circleci/buildpack-deps:stretch
orbs:
  node: circleci/node@5.0.0
  cypress: cypress-io/cypress@1.29.0

jobs:
  build-frontend:
    working_directory: ~/ameciclo/frontend
    steps:
      - cypress/install:
          build: npm run build
      - cypress/run:
          requires:
            - cypress/install
          start: npm start

  build-and-test:
    docker:
      - image: cimg/node:lts

    working_directory: ~/ameciclo/backend

    steps:
      - checkout:
          path: ~/ameciclo
      - node/install:
          install-yarn: true
          node-version: "14.19.0"
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: npm test

workflows:
  build-latest:
    jobs:
      - build-frontend
      - build-and-test
